sonar.projectKey=AleksandraBerezikova_expense-tracker
sonar.organization=aleksandraberezikova

sonar.sources=backend/app,frontend
sonar.tests=backend/tests,frontend/__tests__

sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/.pytest_cache/**,**/venv/**,**/.venv/**,**/.terraform/**,**/__tests__/**
sonar.test.exclusions=**/node_modules/**

sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
