apiVersion: v1
kind: Service
metadata:
  name: expense-tracker-api-nodeport
  labels:
    app: expense-tracker-api
spec:
  type: NodePort
  selector:
    app: expense-tracker-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
      protocol: TCP
